const sequelize = require('../config/database');
const Riviere = require('../models/Riviere')(sequelize);

const rivieresData = [
  // QUÉBEC - RIVIÈRES ÉLITE
  {
    nom: 'Rivière Matapédia',
    nom_anglais: 'Matapedia River',
    pays: 'Canada',
    province_etat: 'Québec',
    region: 'Gaspésie',
    type: 'riviere',
    classe: 1,
    latitude: 48.4567,
    longitude: -67.1234,
    longueur_km: 65.0,
    bassin_versant_km2: 1680,
    nombre_fosses: 45,
    nombre_secteurs: 12,
    type_acces: 'routier',
    difficulte_acces: 'facile',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Septembre',
    temperature_eau: 12.5,
    niveau_eau: 'normal',
    debit_m3s: 45.2,
    clarte: 'excellente',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 85,
    record_saumon: 35,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: true,
    date_limite_tirage: '2025-03-15',
    url_tirage: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/faune/peche-sportive/tirage-au-sort',
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Matapédia est l\'une des rivières à saumon les plus renommées du Québec. Elle offre une pêche exceptionnelle dans un cadre magnifique.',
    historique: 'Historiquement, cette rivière était utilisée par les Premières Nations pour la pêche au saumon. Elle est maintenant protégée et gérée pour la conservation.',
    source_donnees: 'Ministère des Forêts, de la Faune et des Parcs du Québec',
    notes_privilegees: 'Meilleur moment: 6h-9h et 18h-21h. Conditions optimales: température 10-15°C, vent < 15 km/h.'
  },
  {
    nom: 'Rivière Bonaventure',
    nom_anglais: 'Bonaventure River',
    pays: 'Canada',
    province_etat: 'Québec',
    region: 'Gaspésie',
    type: 'riviere',
    classe: 1,
    latitude: 48.2345,
    longitude: -65.6789,
    longueur_km: 125.0,
    bassin_versant_km2: 2840,
    nombre_fosses: 38,
    nombre_secteurs: 15,
    type_acces: 'mixte',
    difficulte_acces: 'modere',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Août',
    temperature_eau: 11.8,
    niveau_eau: 'normal',
    debit_m3s: 52.1,
    clarte: 'excellente',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 82,
    record_saumon: 42,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: true,
    date_limite_tirage: '2025-03-15',
    url_tirage: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/faune/peche-sportive/tirage-au-sort',
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Bonaventure est célèbre pour ses eaux cristallines et sa population de saumons atlantiques.',
    historique: 'Cette rivière a une longue histoire de pêche au saumon et est considérée comme l\'une des plus belles rivières du Québec.',
    source_donnees: 'Ministère des Forêts, de la Faune et des Parcs du Québec',
    notes_privilegees: 'Meilleur moment: 5h-8h et 19h-22h. Conditions optimales: température 8-12°C, vent < 10 km/h.'
  },
  {
    nom: 'Rivière Cascapédia',
    nom_anglais: 'Cascapedia River',
    pays: 'Canada',
    province_etat: 'Québec',
    region: 'Gaspésie',
    type: 'riviere',
    classe: 1,
    latitude: 48.1234,
    longitude: -65.4567,
    longueur_km: 140.0,
    bassin_versant_km2: 3200,
    nombre_fosses: 52,
    nombre_secteurs: 18,
    type_acces: 'mixte',
    difficulte_acces: 'modere',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Juillet',
    temperature_eau: 13.2,
    niveau_eau: 'normal',
    debit_m3s: 48.7,
    clarte: 'excellente',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 88,
    record_saumon: 38,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: true,
    date_limite_tirage: '2025-03-15',
    url_tirage: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/faune/peche-sportive/tirage-au-sort',
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Cascapédia est l\'une des rivières à saumon les plus prestigieuses du Québec.',
    historique: 'Cette rivière a une riche histoire et est connue pour ses gros saumons.',
    source_donnees: 'Ministère des Forêts, de la Faune et des Parcs du Québec',
    notes_privilegees: 'Meilleur moment: 6h-9h et 18h-21h. Conditions optimales: température 12-16°C, vent < 12 km/h.'
  },

  // NOUVELLE-ÉCOSSE
  {
    nom: 'Margaree River',
    nom_anglais: 'Margaree River',
    pays: 'Canada',
    province_etat: 'Nouvelle-Écosse',
    region: 'Cap-Breton',
    type: 'riviere',
    classe: 1,
    latitude: 46.4567,
    longitude: -61.1234,
    longueur_km: 120.0,
    bassin_versant_km2: 1400,
    nombre_fosses: 35,
    nombre_secteurs: 12,
    type_acces: 'routier',
    difficulte_acces: 'facile',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Septembre',
    temperature_eau: 14.5,
    niveau_eau: 'normal',
    debit_m3s: 38.9,
    clarte: 'excellente',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 78,
    record_saumon: 32,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: false,
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Margaree est l\'une des rivières à saumon les plus populaires de la Nouvelle-Écosse.',
    historique: 'Cette rivière a une longue tradition de pêche au saumon.',
    source_donnees: 'Nova Scotia Department of Fisheries and Aquaculture',
    notes_privilegees: 'Meilleur moment: 7h-10h et 17h-20h. Conditions optimales: température 12-16°C, vent < 15 km/h.'
  },

  // NOUVEAU-BRUNSWICK
  {
    nom: 'Miramichi River',
    nom_anglais: 'Miramichi River',
    pays: 'Canada',
    province_etat: 'Nouveau-Brunswick',
    region: 'Miramichi',
    type: 'riviere',
    classe: 1,
    latitude: 46.7890,
    longitude: -65.4567,
    longueur_km: 250.0,
    bassin_versant_km2: 13500,
    nombre_fosses: 85,
    nombre_secteurs: 25,
    type_acces: 'mixte',
    difficulte_acces: 'modere',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Août',
    temperature_eau: 15.2,
    niveau_eau: 'normal',
    debit_m3s: 120.5,
    clarte: 'bonne',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 82,
    record_saumon: 45,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: false,
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Miramichi est l\'une des plus grandes rivières à saumon du Nouveau-Brunswick.',
    historique: 'Cette rivière a une riche histoire de pêche au saumon.',
    source_donnees: 'New Brunswick Department of Natural Resources',
    notes_privilegees: 'Meilleur moment: 6h-9h et 18h-21h. Conditions optimales: température 13-17°C, vent < 15 km/h.'
  },

  // TERRE-NEUVE-ET-LABRADOR
  {
    nom: 'Humber River',
    nom_anglais: 'Humber River',
    pays: 'Canada',
    province_etat: 'Terre-Neuve-et-Labrador',
    region: 'Corner Brook',
    type: 'riviere',
    classe: 1,
    latitude: 48.9012,
    longitude: -57.3456,
    longueur_km: 153.0,
    bassin_versant_km2: 7680,
    nombre_fosses: 42,
    nombre_secteurs: 15,
    type_acces: 'routier',
    difficulte_acces: 'facile',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Juillet',
    temperature_eau: 12.8,
    niveau_eau: 'normal',
    debit_m3s: 65.3,
    clarte: 'excellente',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 85,
    record_saumon: 40,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: false,
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Humber est l\'une des rivières à saumon les plus importantes de Terre-Neuve.',
    historique: 'Cette rivière a une longue tradition de pêche au saumon.',
    source_donnees: 'Newfoundland and Labrador Department of Fisheries and Land Resources',
    notes_privilegees: 'Meilleur moment: 5h-8h et 19h-22h. Conditions optimales: température 10-14°C, vent < 12 km/h.'
  },

  // ÉTATS-UNIS - MAINE
  {
    nom: 'Penobscot River',
    nom_anglais: 'Penobscot River',
    pays: 'États-Unis',
    province_etat: 'Maine',
    region: 'Bangor',
    type: 'riviere',
    classe: 1,
    latitude: 44.8012,
    longitude: -68.7890,
    longueur_km: 563.0,
    bassin_versant_km2: 22000,
    nombre_fosses: 95,
    nombre_secteurs: 30,
    type_acces: 'mixte',
    difficulte_acces: 'modere',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Août',
    temperature_eau: 16.5,
    niveau_eau: 'normal',
    debit_m3s: 350.0,
    clarte: 'bonne',
    statut_conditions: 'excellente',
    statut_conservation: 'excellent',
    population_saumon: 'abondante',
    taille_moyenne_saumon: 80,
    record_saumon: 38,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur', 'Streamer'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: false,
    camping_autorise: true,
    guides_disponibles: true,
    description: 'La rivière Penobscot est l\'une des plus grandes rivières à saumon du Maine.',
    historique: 'Cette rivière a une riche histoire de pêche au saumon.',
    source_donnees: 'Maine Department of Inland Fisheries and Wildlife',
    notes_privilegees: 'Meilleur moment: 6h-9h et 18h-21h. Conditions optimales: température 14-18°C, vent < 15 km/h.'
  },

  // RIVIÈRES STANDARD (CLASSE 2)
  {
    nom: 'Rivière Sainte-Anne',
    nom_anglais: 'Sainte-Anne River',
    pays: 'Canada',
    province_etat: 'Québec',
    region: 'Côte-Nord',
    type: 'riviere',
    classe: 2,
    latitude: 47.1234,
    longitude: -70.5678,
    longueur_km: 85.0,
    bassin_versant_km2: 2100,
    nombre_fosses: 28,
    nombre_secteurs: 10,
    type_acces: 'routier',
    difficulte_acces: 'facile',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Septembre',
    temperature_eau: 11.5,
    niveau_eau: 'normal',
    debit_m3s: 42.3,
    clarte: 'excellente',
    statut_conditions: 'bonne',
    statut_conservation: 'bon',
    population_saumon: 'stable',
    taille_moyenne_saumon: 75,
    record_saumon: 28,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff', 'Elk Hair Caddis'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear', 'Prince Nymph'],
      streamers: ['Woolly Bugger', 'Muddler Minnow']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: true,
    date_limite_tirage: '2025-03-15',
    url_tirage: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/faune/peche-sportive/tirage-au-sort',
    camping_autorise: true,
    guides_disponibles: false,
    description: 'La rivière Sainte-Anne offre une pêche au saumon de qualité dans un environnement préservé.',
    historique: 'Cette rivière est protégée pour la conservation du saumon atlantique.',
    source_donnees: 'Ministère des Forêts, de la Faune et des Parcs du Québec',
    notes_privilegees: 'Meilleur moment: 7h-10h et 17h-20h. Conditions optimales: température 9-13°C, vent < 15 km/h.'
  },

  // RIVIÈRES DÉBUTANT (CLASSE 3)
  {
    nom: 'Rivière du Petit Saguenay',
    nom_anglais: 'Petit Saguenay River',
    pays: 'Canada',
    province_etat: 'Québec',
    region: 'Saguenay-Lac-Saint-Jean',
    type: 'riviere',
    classe: 3,
    latitude: 48.2345,
    longitude: -70.1234,
    longueur_km: 45.0,
    bassin_versant_km2: 850,
    nombre_fosses: 15,
    nombre_secteurs: 6,
    type_acces: 'routier',
    difficulte_acces: 'facile',
    saison_peche: 'Juin à Octobre',
    saison_principale: 'Août',
    temperature_eau: 13.8,
    niveau_eau: 'normal',
    debit_m3s: 25.6,
    clarte: 'bonne',
    statut_conditions: 'moyenne',
    statut_conservation: 'bon',
    population_saumon: 'stable',
    taille_moyenne_saumon: 65,
    record_saumon: 22,
    mouches_recommandees: {
      seches: ['Adams', 'Royal Wulff'],
      nymphes: ['Pheasant Tail', 'Hare\'s Ear'],
      streamers: ['Woolly Bugger']
    },
    techniques_recommandees: ['Lancer à la mouche sèche', 'Nymphe sous indicateur'],
    reglementation: 'Permis de pêche requis. Limite quotidienne: 1 saumon par jour.',
    permis_requis: true,
    tirage_au_sort: false,
    camping_autorise: true,
    guides_disponibles: false,
    description: 'La rivière du Petit Saguenay est idéale pour les débutants en pêche au saumon.',
    historique: 'Cette rivière est plus accessible et convient bien aux pêcheurs débutants.',
    source_donnees: 'Ministère des Forêts, de la Faune et des Parcs du Québec',
    notes_privilegees: 'Meilleur moment: 8h-11h et 16h-19h. Conditions optimales: température 12-16°C, vent < 20 km/h.'
  }
];

async function seedRivieres() {
  try {
    console.log('🌊 Seeding des rivières à saumon atlantique...');
    
    // Supprimer les données existantes
    await Riviere.destroy({ where: {} });
    
    // Insérer les nouvelles données
    await Riviere.bulkCreate(rivieresData);
    
    console.log(`✅ ${rivieresData.length} rivières créées avec succès !`);
    
    // Afficher un résumé
    const eliteCount = rivieresData.filter(r => r.classe === 1).length;
    const standardCount = rivieresData.filter(r => r.classe === 2).length;
    const debutantCount = rivieresData.filter(r => r.classe === 3).length;
    
    console.log(`📊 Résumé:`);
    console.log(`   - Rivières Elite (Classe 1): ${eliteCount}`);
    console.log(`   - Rivières Standard (Classe 2): ${standardCount}`);
    console.log(`   - Rivières Débutant (Classe 3): ${debutantCount}`);
    console.log(`   - Total: ${rivieresData.length} rivières`);
    
  } catch (error) {
    console.error('❌ Erreur lors du seeding des rivières:', error);
    throw error;
  }
}

module.exports = { seedRivieres };
